server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s

logger:
  dir: logs
  file: all.log

storage:
  database:
    driver: postgres
    source: "host=postgres user=user password=password dbname=alphinium sslmode=disable"

forum:
  postsPerPage: 30