// Code generated by ent, DO NOT EDIT.

package category

const (
	// Label holds the string label denoting the category type in the database.
	Label = "category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeSubcategories holds the string denoting the subcategories edge name in mutations.
	EdgeSubcategories = "subcategories"
	// Table holds the table name of the category in the database.
	Table = "categories"
	// SubcategoriesTable is the table that holds the subcategories relation/edge.
	SubcategoriesTable = "subcategories"
	// SubcategoriesInverseTable is the table name for the Subcategory entity.
	// It exists in this package in order to avoid circular dependency with the "subcategory" package.
	SubcategoriesInverseTable = "subcategories"
	// SubcategoriesColumn is the table column denoting the subcategories relation/edge.
	SubcategoriesColumn = "category_id"
)

// Columns holds all SQL columns for category fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
