// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Subcategory is the predicate function for subcategory builders.
type Subcategory func(*sql.Selector)

// Thread is the predicate function for thread builders.
type Thread func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserMetadata is the predicate function for usermetadata builders.
type UserMetadata func(*sql.Selector)
