// Code generated by ent, DO NOT EDIT.

package thread

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Skijetler/alphinium/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// DescriptionID applies equality check predicate on the "description_id" field. It's identical to DescriptionIDEQ.
func DescriptionID(v uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescriptionID), v))
	})
}

// SubcategoryID applies equality check predicate on the "subcategory_id" field. It's identical to SubcategoryIDEQ.
func SubcategoryID(v uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSubcategoryID), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Thread {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Thread {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// DescriptionIDEQ applies the EQ predicate on the "description_id" field.
func DescriptionIDEQ(v uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescriptionID), v))
	})
}

// DescriptionIDNEQ applies the NEQ predicate on the "description_id" field.
func DescriptionIDNEQ(v uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDescriptionID), v))
	})
}

// DescriptionIDIn applies the In predicate on the "description_id" field.
func DescriptionIDIn(vs ...uint64) predicate.Thread {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDescriptionID), v...))
	})
}

// DescriptionIDNotIn applies the NotIn predicate on the "description_id" field.
func DescriptionIDNotIn(vs ...uint64) predicate.Thread {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDescriptionID), v...))
	})
}

// SubcategoryIDEQ applies the EQ predicate on the "subcategory_id" field.
func SubcategoryIDEQ(v uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSubcategoryID), v))
	})
}

// SubcategoryIDNEQ applies the NEQ predicate on the "subcategory_id" field.
func SubcategoryIDNEQ(v uint64) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSubcategoryID), v))
	})
}

// SubcategoryIDIn applies the In predicate on the "subcategory_id" field.
func SubcategoryIDIn(vs ...uint64) predicate.Thread {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSubcategoryID), v...))
	})
}

// SubcategoryIDNotIn applies the NotIn predicate on the "subcategory_id" field.
func SubcategoryIDNotIn(vs ...uint64) predicate.Thread {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Thread(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSubcategoryID), v...))
	})
}

// HasSubcategory applies the HasEdge predicate on the "subcategory" edge.
func HasSubcategory() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SubcategoryTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubcategoryTable, SubcategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubcategoryWith applies the HasEdge predicate on the "subcategory" edge with a given conditions (other predicates).
func HasSubcategoryWith(preds ...predicate.Subcategory) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SubcategoryInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubcategoryTable, SubcategoryColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDescription applies the HasEdge predicate on the "description" edge.
func HasDescription() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DescriptionTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DescriptionTable, DescriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDescriptionWith applies the HasEdge predicate on the "description" edge with a given conditions (other predicates).
func HasDescriptionWith(preds ...predicate.Post) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DescriptionInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DescriptionTable, DescriptionColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPosts applies the HasEdge predicate on the "posts" edge.
func HasPosts() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PostsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PostsTable, PostsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostsWith applies the HasEdge predicate on the "posts" edge with a given conditions (other predicates).
func HasPostsWith(preds ...predicate.Post) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PostsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PostsTable, PostsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Thread) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Thread) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Thread) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		p(s.Not())
	})
}
