// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Skijetler/alphinium/pkg/ent/schema"
	"github.com/Skijetler/alphinium/pkg/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[5].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
}
