// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Skijetler/alphinium/pkg/ent/category"
	"github.com/Skijetler/alphinium/pkg/ent/predicate"
	"github.com/Skijetler/alphinium/pkg/ent/subcategory"
	"github.com/Skijetler/alphinium/pkg/ent/thread"
)

// SubcategoryUpdate is the builder for updating Subcategory entities.
type SubcategoryUpdate struct {
	config
	hooks    []Hook
	mutation *SubcategoryMutation
}

// Where appends a list predicates to the SubcategoryUpdate builder.
func (su *SubcategoryUpdate) Where(ps ...predicate.Subcategory) *SubcategoryUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SubcategoryUpdate) SetName(s string) *SubcategoryUpdate {
	su.mutation.SetName(s)
	return su
}

// SetDescription sets the "description" field.
func (su *SubcategoryUpdate) SetDescription(s string) *SubcategoryUpdate {
	su.mutation.SetDescription(s)
	return su
}

// SetCategoryID sets the "category_id" field.
func (su *SubcategoryUpdate) SetCategoryID(u uint64) *SubcategoryUpdate {
	su.mutation.SetCategoryID(u)
	return su
}

// SetCategory sets the "category" edge to the Category entity.
func (su *SubcategoryUpdate) SetCategory(c *Category) *SubcategoryUpdate {
	return su.SetCategoryID(c.ID)
}

// AddThreadIDs adds the "threads" edge to the Thread entity by IDs.
func (su *SubcategoryUpdate) AddThreadIDs(ids ...uint64) *SubcategoryUpdate {
	su.mutation.AddThreadIDs(ids...)
	return su
}

// AddThreads adds the "threads" edges to the Thread entity.
func (su *SubcategoryUpdate) AddThreads(t ...*Thread) *SubcategoryUpdate {
	ids := make([]uint64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return su.AddThreadIDs(ids...)
}

// Mutation returns the SubcategoryMutation object of the builder.
func (su *SubcategoryUpdate) Mutation() *SubcategoryMutation {
	return su.mutation
}

// ClearCategory clears the "category" edge to the Category entity.
func (su *SubcategoryUpdate) ClearCategory() *SubcategoryUpdate {
	su.mutation.ClearCategory()
	return su
}

// ClearThreads clears all "threads" edges to the Thread entity.
func (su *SubcategoryUpdate) ClearThreads() *SubcategoryUpdate {
	su.mutation.ClearThreads()
	return su
}

// RemoveThreadIDs removes the "threads" edge to Thread entities by IDs.
func (su *SubcategoryUpdate) RemoveThreadIDs(ids ...uint64) *SubcategoryUpdate {
	su.mutation.RemoveThreadIDs(ids...)
	return su
}

// RemoveThreads removes "threads" edges to Thread entities.
func (su *SubcategoryUpdate) RemoveThreads(t ...*Thread) *SubcategoryUpdate {
	ids := make([]uint64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return su.RemoveThreadIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SubcategoryUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		if err = su.check(); err != nil {
			return 0, err
		}
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SubcategoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = su.check(); err != nil {
				return 0, err
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SubcategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SubcategoryUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SubcategoryUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SubcategoryUpdate) check() error {
	if _, ok := su.mutation.CategoryID(); su.mutation.CategoryCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Subcategory.category"`)
	}
	return nil
}

func (su *SubcategoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   subcategory.Table,
			Columns: subcategory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: subcategory.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subcategory.FieldName,
		})
	}
	if value, ok := su.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subcategory.FieldDescription,
		})
	}
	if su.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subcategory.CategoryTable,
			Columns: []string{subcategory.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: category.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subcategory.CategoryTable,
			Columns: []string{subcategory.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.ThreadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subcategory.ThreadsTable,
			Columns: []string{subcategory.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: thread.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedThreadsIDs(); len(nodes) > 0 && !su.mutation.ThreadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subcategory.ThreadsTable,
			Columns: []string{subcategory.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: thread.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ThreadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subcategory.ThreadsTable,
			Columns: []string{subcategory.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: thread.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// SubcategoryUpdateOne is the builder for updating a single Subcategory entity.
type SubcategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubcategoryMutation
}

// SetName sets the "name" field.
func (suo *SubcategoryUpdateOne) SetName(s string) *SubcategoryUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetDescription sets the "description" field.
func (suo *SubcategoryUpdateOne) SetDescription(s string) *SubcategoryUpdateOne {
	suo.mutation.SetDescription(s)
	return suo
}

// SetCategoryID sets the "category_id" field.
func (suo *SubcategoryUpdateOne) SetCategoryID(u uint64) *SubcategoryUpdateOne {
	suo.mutation.SetCategoryID(u)
	return suo
}

// SetCategory sets the "category" edge to the Category entity.
func (suo *SubcategoryUpdateOne) SetCategory(c *Category) *SubcategoryUpdateOne {
	return suo.SetCategoryID(c.ID)
}

// AddThreadIDs adds the "threads" edge to the Thread entity by IDs.
func (suo *SubcategoryUpdateOne) AddThreadIDs(ids ...uint64) *SubcategoryUpdateOne {
	suo.mutation.AddThreadIDs(ids...)
	return suo
}

// AddThreads adds the "threads" edges to the Thread entity.
func (suo *SubcategoryUpdateOne) AddThreads(t ...*Thread) *SubcategoryUpdateOne {
	ids := make([]uint64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return suo.AddThreadIDs(ids...)
}

// Mutation returns the SubcategoryMutation object of the builder.
func (suo *SubcategoryUpdateOne) Mutation() *SubcategoryMutation {
	return suo.mutation
}

// ClearCategory clears the "category" edge to the Category entity.
func (suo *SubcategoryUpdateOne) ClearCategory() *SubcategoryUpdateOne {
	suo.mutation.ClearCategory()
	return suo
}

// ClearThreads clears all "threads" edges to the Thread entity.
func (suo *SubcategoryUpdateOne) ClearThreads() *SubcategoryUpdateOne {
	suo.mutation.ClearThreads()
	return suo
}

// RemoveThreadIDs removes the "threads" edge to Thread entities by IDs.
func (suo *SubcategoryUpdateOne) RemoveThreadIDs(ids ...uint64) *SubcategoryUpdateOne {
	suo.mutation.RemoveThreadIDs(ids...)
	return suo
}

// RemoveThreads removes "threads" edges to Thread entities.
func (suo *SubcategoryUpdateOne) RemoveThreads(t ...*Thread) *SubcategoryUpdateOne {
	ids := make([]uint64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return suo.RemoveThreadIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SubcategoryUpdateOne) Select(field string, fields ...string) *SubcategoryUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Subcategory entity.
func (suo *SubcategoryUpdateOne) Save(ctx context.Context) (*Subcategory, error) {
	var (
		err  error
		node *Subcategory
	)
	if len(suo.hooks) == 0 {
		if err = suo.check(); err != nil {
			return nil, err
		}
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SubcategoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suo.check(); err != nil {
				return nil, err
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, suo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Subcategory)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SubcategoryMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SubcategoryUpdateOne) SaveX(ctx context.Context) *Subcategory {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SubcategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SubcategoryUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SubcategoryUpdateOne) check() error {
	if _, ok := suo.mutation.CategoryID(); suo.mutation.CategoryCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Subcategory.category"`)
	}
	return nil
}

func (suo *SubcategoryUpdateOne) sqlSave(ctx context.Context) (_node *Subcategory, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   subcategory.Table,
			Columns: subcategory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: subcategory.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subcategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subcategory.FieldID)
		for _, f := range fields {
			if !subcategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subcategory.FieldName,
		})
	}
	if value, ok := suo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subcategory.FieldDescription,
		})
	}
	if suo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subcategory.CategoryTable,
			Columns: []string{subcategory.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: category.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subcategory.CategoryTable,
			Columns: []string{subcategory.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.ThreadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subcategory.ThreadsTable,
			Columns: []string{subcategory.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: thread.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedThreadsIDs(); len(nodes) > 0 && !suo.mutation.ThreadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subcategory.ThreadsTable,
			Columns: []string{subcategory.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: thread.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ThreadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subcategory.ThreadsTable,
			Columns: []string{subcategory.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: thread.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subcategory{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
