// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Skijetler/alphinium/pkg/ent/post"
	"github.com/Skijetler/alphinium/pkg/ent/predicate"
	"github.com/Skijetler/alphinium/pkg/ent/subcategory"
	"github.com/Skijetler/alphinium/pkg/ent/thread"
)

// ThreadQuery is the builder for querying Thread entities.
type ThreadQuery struct {
	config
	limit           *int
	offset          *int
	unique          *bool
	order           []OrderFunc
	fields          []string
	predicates      []predicate.Thread
	withSubcategory *SubcategoryQuery
	withDescription *PostQuery
	withPosts       *PostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ThreadQuery builder.
func (tq *ThreadQuery) Where(ps ...predicate.Thread) *ThreadQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit adds a limit step to the query.
func (tq *ThreadQuery) Limit(limit int) *ThreadQuery {
	tq.limit = &limit
	return tq
}

// Offset adds an offset step to the query.
func (tq *ThreadQuery) Offset(offset int) *ThreadQuery {
	tq.offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *ThreadQuery) Unique(unique bool) *ThreadQuery {
	tq.unique = &unique
	return tq
}

// Order adds an order step to the query.
func (tq *ThreadQuery) Order(o ...OrderFunc) *ThreadQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QuerySubcategory chains the current query on the "subcategory" edge.
func (tq *ThreadQuery) QuerySubcategory() *SubcategoryQuery {
	query := &SubcategoryQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(thread.Table, thread.FieldID, selector),
			sqlgraph.To(subcategory.Table, subcategory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, thread.SubcategoryTable, thread.SubcategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDescription chains the current query on the "description" edge.
func (tq *ThreadQuery) QueryDescription() *PostQuery {
	query := &PostQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(thread.Table, thread.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, thread.DescriptionTable, thread.DescriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPosts chains the current query on the "posts" edge.
func (tq *ThreadQuery) QueryPosts() *PostQuery {
	query := &PostQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(thread.Table, thread.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, thread.PostsTable, thread.PostsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Thread entity from the query.
// Returns a *NotFoundError when no Thread was found.
func (tq *ThreadQuery) First(ctx context.Context) (*Thread, error) {
	nodes, err := tq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{thread.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *ThreadQuery) FirstX(ctx context.Context) *Thread {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Thread ID from the query.
// Returns a *NotFoundError when no Thread ID was found.
func (tq *ThreadQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = tq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{thread.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *ThreadQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Thread entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Thread entity is found.
// Returns a *NotFoundError when no Thread entities are found.
func (tq *ThreadQuery) Only(ctx context.Context) (*Thread, error) {
	nodes, err := tq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{thread.Label}
	default:
		return nil, &NotSingularError{thread.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *ThreadQuery) OnlyX(ctx context.Context) *Thread {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Thread ID in the query.
// Returns a *NotSingularError when more than one Thread ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *ThreadQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = tq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{thread.Label}
	default:
		err = &NotSingularError{thread.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *ThreadQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Threads.
func (tq *ThreadQuery) All(ctx context.Context) ([]*Thread, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tq *ThreadQuery) AllX(ctx context.Context) []*Thread {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Thread IDs.
func (tq *ThreadQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := tq.Select(thread.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *ThreadQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *ThreadQuery) Count(ctx context.Context) (int, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tq *ThreadQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *ThreadQuery) Exist(ctx context.Context) (bool, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *ThreadQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ThreadQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *ThreadQuery) Clone() *ThreadQuery {
	if tq == nil {
		return nil
	}
	return &ThreadQuery{
		config:          tq.config,
		limit:           tq.limit,
		offset:          tq.offset,
		order:           append([]OrderFunc{}, tq.order...),
		predicates:      append([]predicate.Thread{}, tq.predicates...),
		withSubcategory: tq.withSubcategory.Clone(),
		withDescription: tq.withDescription.Clone(),
		withPosts:       tq.withPosts.Clone(),
		// clone intermediate query.
		sql:    tq.sql.Clone(),
		path:   tq.path,
		unique: tq.unique,
	}
}

// WithSubcategory tells the query-builder to eager-load the nodes that are connected to
// the "subcategory" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *ThreadQuery) WithSubcategory(opts ...func(*SubcategoryQuery)) *ThreadQuery {
	query := &SubcategoryQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withSubcategory = query
	return tq
}

// WithDescription tells the query-builder to eager-load the nodes that are connected to
// the "description" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *ThreadQuery) WithDescription(opts ...func(*PostQuery)) *ThreadQuery {
	query := &PostQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withDescription = query
	return tq
}

// WithPosts tells the query-builder to eager-load the nodes that are connected to
// the "posts" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *ThreadQuery) WithPosts(opts ...func(*PostQuery)) *ThreadQuery {
	query := &PostQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withPosts = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Thread.Query().
//		GroupBy(thread.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *ThreadQuery) GroupBy(field string, fields ...string) *ThreadGroupBy {
	grbuild := &ThreadGroupBy{config: tq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tq.sqlQuery(ctx), nil
	}
	grbuild.label = thread.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Thread.Query().
//		Select(thread.FieldName).
//		Scan(ctx, &v)
func (tq *ThreadQuery) Select(fields ...string) *ThreadSelect {
	tq.fields = append(tq.fields, fields...)
	selbuild := &ThreadSelect{ThreadQuery: tq}
	selbuild.label = thread.Label
	selbuild.flds, selbuild.scan = &tq.fields, selbuild.Scan
	return selbuild
}

func (tq *ThreadQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tq.fields {
		if !thread.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *ThreadQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Thread, error) {
	var (
		nodes       = []*Thread{}
		_spec       = tq.querySpec()
		loadedTypes = [3]bool{
			tq.withSubcategory != nil,
			tq.withDescription != nil,
			tq.withPosts != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Thread).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Thread{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withSubcategory; query != nil {
		if err := tq.loadSubcategory(ctx, query, nodes, nil,
			func(n *Thread, e *Subcategory) { n.Edges.Subcategory = e }); err != nil {
			return nil, err
		}
	}
	if query := tq.withDescription; query != nil {
		if err := tq.loadDescription(ctx, query, nodes, nil,
			func(n *Thread, e *Post) { n.Edges.Description = e }); err != nil {
			return nil, err
		}
	}
	if query := tq.withPosts; query != nil {
		if err := tq.loadPosts(ctx, query, nodes,
			func(n *Thread) { n.Edges.Posts = []*Post{} },
			func(n *Thread, e *Post) { n.Edges.Posts = append(n.Edges.Posts, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *ThreadQuery) loadSubcategory(ctx context.Context, query *SubcategoryQuery, nodes []*Thread, init func(*Thread), assign func(*Thread, *Subcategory)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Thread)
	for i := range nodes {
		fk := nodes[i].SubcategoryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(subcategory.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subcategory_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tq *ThreadQuery) loadDescription(ctx context.Context, query *PostQuery, nodes []*Thread, init func(*Thread), assign func(*Thread, *Post)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Thread)
	for i := range nodes {
		fk := nodes[i].DescriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(post.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "description_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tq *ThreadQuery) loadPosts(ctx context.Context, query *PostQuery, nodes []*Thread, init func(*Thread), assign func(*Thread, *Post)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Thread)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Post(func(s *sql.Selector) {
		s.Where(sql.InValues(thread.PostsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ThreadID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "thread_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tq *ThreadQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.fields
	if len(tq.fields) > 0 {
		_spec.Unique = tq.unique != nil && *tq.unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *ThreadQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (tq *ThreadQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   thread.Table,
			Columns: thread.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: thread.FieldID,
			},
		},
		From:   tq.sql,
		Unique: true,
	}
	if unique := tq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, thread.FieldID)
		for i := range fields {
			if fields[i] != thread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *ThreadQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(thread.Table)
	columns := tq.fields
	if len(columns) == 0 {
		columns = thread.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.unique != nil && *tq.unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ThreadGroupBy is the group-by builder for Thread entities.
type ThreadGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *ThreadGroupBy) Aggregate(fns ...AggregateFunc) *ThreadGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tgb *ThreadGroupBy) Scan(ctx context.Context, v any) error {
	query, err := tgb.path(ctx)
	if err != nil {
		return err
	}
	tgb.sql = query
	return tgb.sqlScan(ctx, v)
}

func (tgb *ThreadGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range tgb.fields {
		if !thread.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tgb *ThreadGroupBy) sqlQuery() *sql.Selector {
	selector := tgb.sql.Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tgb.fields)+len(tgb.fns))
		for _, f := range tgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tgb.fields...)...)
}

// ThreadSelect is the builder for selecting fields of Thread entities.
type ThreadSelect struct {
	*ThreadQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ts *ThreadSelect) Scan(ctx context.Context, v any) error {
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	ts.sql = ts.ThreadQuery.sqlQuery(ctx)
	return ts.sqlScan(ctx, v)
}

func (ts *ThreadSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := ts.sql.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
